#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.0.5 on Thu Jun 29 16:17:15 2023
#

# This is an automatically generated file.
# Manual changes will be overwritten without warning!

import wx
from MainGUI import MainGUI
import sys
f = open("output.log","w",encoding="utf-8")
sys.stderr = f
sys.stdout = f


class Ayrimla(wx.App):
	def OnInit(self):
		self.main_gui = MainGUI(None, wx.ID_ANY, "")
		self.SetTopWindow(self.main_gui)
		self.main_gui.Show()
		return True

# end of class Ayrimla

if __name__ == "__main__":
	ayrimla = Ayrimla(0)
	ayrimla.MainLoop()
